# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_raspi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ST_workerStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.ST_workerStack.setGeometry(QtCore.QRect(0, 50, 481, 221))
        self.ST_workerStack.setObjectName("ST_workerStack")
        self.SC_welcomeScreen = QtWidgets.QWidget()
        self.SC_welcomeScreen.setObjectName("SC_welcomeScreen")
        self.LB_welcomeText = QtWidgets.QLabel(self.SC_welcomeScreen)
        self.LB_welcomeText.setGeometry(QtCore.QRect(80, 80, 281, 41))
        self.LB_welcomeText.setObjectName("LB_welcomeText")
        self.ST_workerStack.addWidget(self.SC_welcomeScreen)
        self.SC_sonosScreen = QtWidgets.QWidget()
        self.SC_sonosScreen.setObjectName("SC_sonosScreen")
        self.LB_sonosScreen = QtWidgets.QLabel(self.SC_sonosScreen)
        self.LB_sonosScreen.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.LB_sonosScreen.setObjectName("LB_sonosScreen")
        self.BT_sonosPlay = QtWidgets.QPushButton(self.SC_sonosScreen)
        self.BT_sonosPlay.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.BT_sonosPlay.setObjectName("BT_sonosPlay")
        self.SL_volume = QtWidgets.QSlider(self.SC_sonosScreen)
        self.SL_volume.setGeometry(QtCore.QRect(440, 40, 19, 160))
        self.SL_volume.setOrientation(QtCore.Qt.Vertical)
        self.SL_volume.setObjectName("SL_volume")
        self.BT_mute = QtWidgets.QPushButton(self.SC_sonosScreen)
        self.BT_mute.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.BT_mute.setObjectName("BT_mute")
        self.BT_stop = QtWidgets.QPushButton(self.SC_sonosScreen)
        self.BT_stop.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.BT_stop.setObjectName("BT_stop")
        self.BT_skip = QtWidgets.QPushButton(self.SC_sonosScreen)
        self.BT_skip.setGeometry(QtCore.QRect(100, 80, 75, 23))
        self.BT_skip.setObjectName("BT_skip")
        self.LB_currentlyPlaying = QtWidgets.QLabel(self.SC_sonosScreen)
        self.LB_currentlyPlaying.setGeometry(QtCore.QRect(10, 170, 281, 16))
        self.LB_currentlyPlaying.setObjectName("LB_currentlyPlaying")
        self.ST_workerStack.addWidget(self.SC_sonosScreen)
        self.SC_weatherScreen = QtWidgets.QWidget()
        self.SC_weatherScreen.setObjectName("SC_weatherScreen")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.SC_weatherScreen)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 481, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.LB_weatherScreen = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_weatherScreen.setObjectName("LB_weatherScreen")
        self.horizontalLayout.addWidget(self.LB_weatherScreen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LB_oldFreezer = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_oldFreezer.setObjectName("LB_oldFreezer")
        self.gridLayout.addWidget(self.LB_oldFreezer, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.LB_newFreezer = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LB_newFreezer.setObjectName("LB_newFreezer")
        self.gridLayout.addWidget(self.LB_newFreezer, 2, 1, 1, 1)
        self.LB_internalTemp = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_internalTemp.sizePolicy().hasHeightForWidth())
        self.LB_internalTemp.setSizePolicy(sizePolicy)
        self.LB_internalTemp.setObjectName("LB_internalTemp")
        self.gridLayout.addWidget(self.LB_internalTemp, 0, 1, 1, 1)
        self.LCD_newFreezer = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LCD_newFreezer.setProperty("value", -16.2)
        self.LCD_newFreezer.setObjectName("LCD_newFreezer")
        self.gridLayout.addWidget(self.LCD_newFreezer, 2, 2, 1, 1)
        self.LCD_piTemp = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LCD_piTemp.setSmallDecimalPoint(True)
        self.LCD_piTemp.setProperty("intValue", 40)
        self.LCD_piTemp.setObjectName("LCD_piTemp")
        self.gridLayout.addWidget(self.LCD_piTemp, 0, 2, 1, 1)
        self.LCD_oldFreezer = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LCD_oldFreezer.setProperty("value", -15.5)
        self.LCD_oldFreezer.setObjectName("LCD_oldFreezer")
        self.gridLayout.addWidget(self.LCD_oldFreezer, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.ST_workerStack.addWidget(self.SC_weatherScreen)
        self.SC_log = QtWidgets.QWidget()
        self.SC_log.setObjectName("SC_log")
        self.TE_Debug = QtWidgets.QTextEdit(self.SC_log)
        self.TE_Debug.setGeometry(QtCore.QRect(10, 0, 461, 221))
        self.TE_Debug.setObjectName("TE_Debug")
        self.ST_workerStack.addWidget(self.SC_log)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopSelectionBar = QtWidgets.QHBoxLayout()
        self.TopSelectionBar.setObjectName("TopSelectionBar")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopSelectionBar.addItem(spacerItem4)
        self.BT_openHomeScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openHomeScreen.setObjectName("BT_openHomeScreen")
        self.TopSelectionBar.addWidget(self.BT_openHomeScreen)
        self.BT_openSonosScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openSonosScreen.setObjectName("BT_openSonosScreen")
        self.TopSelectionBar.addWidget(self.BT_openSonosScreen)
        self.BT_openWeatherScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openWeatherScreen.setObjectName("BT_openWeatherScreen")
        self.TopSelectionBar.addWidget(self.BT_openWeatherScreen)
        self.BT_openLogScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openLogScreen.setObjectName("BT_openLogScreen")
        self.TopSelectionBar.addWidget(self.BT_openLogScreen)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopSelectionBar.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.TopSelectionBar)
        self.LN_boarderLine = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.LN_boarderLine.setEnabled(False)
        self.LN_boarderLine.setAutoFillBackground(False)
        self.LN_boarderLine.setStyleSheet("color: rgb(0, 85, 255)")
        self.LN_boarderLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LN_boarderLine.setLineWidth(3)
        self.LN_boarderLine.setMidLineWidth(3)
        self.LN_boarderLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.LN_boarderLine.setObjectName("LN_boarderLine")
        self.verticalLayout.addWidget(self.LN_boarderLine)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ST_workerStack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LB_welcomeText.setText(_translate("MainWindow", "Hi and welcome to the Home Automation control interface"))
        self.LB_sonosScreen.setText(_translate("MainWindow", "This is the sonos screen"))
        self.BT_sonosPlay.setText(_translate("MainWindow", "Play"))
        self.BT_mute.setText(_translate("MainWindow", "Mute"))
        self.BT_stop.setText(_translate("MainWindow", "Stop"))
        self.BT_skip.setText(_translate("MainWindow", "Skip"))
        self.LB_currentlyPlaying.setText(_translate("MainWindow", "currently playing..."))
        self.LB_weatherScreen.setText(_translate("MainWindow", "This is the weather screen"))
        self.LB_oldFreezer.setText(_translate("MainWindow", "Temp alter Gefrierschrank"))
        self.LB_newFreezer.setText(_translate("MainWindow", "Temp neuer Gefrierschrank"))
        self.LB_internalTemp.setText(_translate("MainWindow", "internal Temp"))
        self.BT_openHomeScreen.setText(_translate("MainWindow", "HOME"))
        self.BT_openSonosScreen.setText(_translate("MainWindow", "SONOS"))
        self.BT_openWeatherScreen.setText(_translate("MainWindow", "WETTER"))
        self.BT_openLogScreen.setText(_translate("MainWindow", "LOG"))

