# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_raspi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ST_workerStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.ST_workerStack.setGeometry(QtCore.QRect(-1, 39, 481, 231))
        self.ST_workerStack.setObjectName("ST_workerStack")
        self.SC_welcomeScreen = QtWidgets.QWidget()
        self.SC_welcomeScreen.setObjectName("SC_welcomeScreen")
        self.LB_welcomeText = QtWidgets.QLabel(self.SC_welcomeScreen)
        self.LB_welcomeText.setGeometry(QtCore.QRect(80, 80, 281, 41))
        self.LB_welcomeText.setObjectName("LB_welcomeText")
        self.ST_workerStack.addWidget(self.SC_welcomeScreen)
        self.SC_sonosScreen = QtWidgets.QWidget()
        self.SC_sonosScreen.setObjectName("SC_sonosScreen")
        self.LB_sonosScreen = QtWidgets.QLabel(self.SC_sonosScreen)
        self.LB_sonosScreen.setGeometry(QtCore.QRect(170, 120, 141, 16))
        self.LB_sonosScreen.setObjectName("LB_sonosScreen")
        self.ST_workerStack.addWidget(self.SC_sonosScreen)
        self.SC_weatherScreen = QtWidgets.QWidget()
        self.SC_weatherScreen.setObjectName("SC_weatherScreen")
        self.LB_weatherScreen = QtWidgets.QLabel(self.SC_weatherScreen)
        self.LB_weatherScreen.setGeometry(QtCore.QRect(180, 120, 141, 16))
        self.LB_weatherScreen.setObjectName("LB_weatherScreen")
        self.ST_workerStack.addWidget(self.SC_weatherScreen)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopSelectionBar = QtWidgets.QHBoxLayout()
        self.TopSelectionBar.setObjectName("TopSelectionBar")
        self.BT_openHomeScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openHomeScreen.setObjectName("BT_openHomeScreen")
        self.TopSelectionBar.addWidget(self.BT_openHomeScreen)
        self.BT_openSonosScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openSonosScreen.setObjectName("BT_openSonosScreen")
        self.TopSelectionBar.addWidget(self.BT_openSonosScreen)
        self.BT_openWeatherScreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.BT_openWeatherScreen.setObjectName("BT_openWeatherScreen")
        self.TopSelectionBar.addWidget(self.BT_openWeatherScreen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopSelectionBar.addItem(spacerItem)
        self.verticalLayout.addLayout(self.TopSelectionBar)
        self.LN_boarderLine = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.LN_boarderLine.setEnabled(False)
        self.LN_boarderLine.setAutoFillBackground(False)
        self.LN_boarderLine.setStyleSheet("color: rgb(0, 85, 255)")
        self.LN_boarderLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LN_boarderLine.setLineWidth(3)
        self.LN_boarderLine.setMidLineWidth(3)
        self.LN_boarderLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.LN_boarderLine.setObjectName("LN_boarderLine")
        self.verticalLayout.addWidget(self.LN_boarderLine)
        self.ST_workerStack.raise_()
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ST_workerStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LB_welcomeText.setText(_translate("MainWindow", "Hi and welcome to the Home Automation control interface"))
        self.LB_sonosScreen.setText(_translate("MainWindow", "This is the sonos screen"))
        self.LB_weatherScreen.setText(_translate("MainWindow", "This is the weather screen"))
        self.BT_openHomeScreen.setText(_translate("MainWindow", "HOME"))
        self.BT_openSonosScreen.setText(_translate("MainWindow", "SONOS"))
        self.BT_openWeatherScreen.setText(_translate("MainWindow", "WETTER"))

